# Generated by Django 2.2.7 on 2019-12-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('Date', models.DateField()),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
    ]
